title:            Bennett Piater's Blog
tagline:          Welcome to my Blog!
description:      I will share stories about my life with the LORD and programming.
canonical:        http://bennett.piater.name
url:              http://bennett.piater.name

# Owner/author information
owner:
  name:           Bennett Piater
  avatar:         avatar.png
  bio:            "My life belongs to the LORD. Soli Deo Gloria!"
  email:          bennett@piater.name
  twitter:        clawoflight
  github:         clawoflight
  instagram:
  dribbble:
  disqus:         bennetts-blog
  location:       "Innsbruck, Austria"
  # Plug in your disqus shortname!

tools:
  standards:      ""
  software:       ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: Me
    url: /me
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Photography
    url: /photography
  #- title: Cole Who?
  #  url: http://coletownsend.com
  #  external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Vienna
future:      false
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
  style: :compressed

gems:
  - jekyll-sitemap

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:categories/:year/:month/:day/:title/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

defaults:
-
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "scripture"
